### ISSUE TITLE
Key on Keyboard doesn't work

### ISSUE THREAD

**Issue by pyxsor** [Nywaa/Sound-Brot#1]
Browser Chrome. Tested on Physical Keyboard and On Screen Keyboard doesn't play the sound. 

# NB. read this while continuously clicking Button "S"

**Comment by Nywaa** [comment]
Thanks for the feedbacks. As for now keyboard button is not yet implemented to play sound. 
I will implement it soon.

**Comment by Nywaa** [comment]
Keyboard is now can play a sound
